### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'size'

### ISSUE THREAD

**Issue by t9lex** [phanein/deepwalk#137]
TypeError: __init__() got an unexpected keyword argument 'size'

**Comment by t9lex** [comment]
i kown it is the version problem,but what should i do?

**Comment by Daraan** [comment]
Use `pip install gensim==3.8.3` that works with python3.9 and the provided setup.

**Comment by t9lex** [comment]
think you.

**Comment by jtyoui** [comment]
![image](https://github.com/phanein/deepwalk/assets/28988355/30e54f9e-ced0-445a-a5a2-75f9bdaded07)
replace this
